"""initial_schema

Revision ID: c6fcc931b57d
Revises: 
Create Date: 2025-11-16 05:59:03.793486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fcc931b57d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='serverstatus'), nullable=True),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', name='healthstatus'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_thresholds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('CPU', 'MEMORY', 'DISK', 'NETWORK', 'SERVICE', name='alerttype'), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('comparison', sa.Enum('GT', 'LT', name='comparisontype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_thresholds_server_id'), 'alert_thresholds', ['server_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CPU', 'MEMORY', 'DISK', 'NETWORK', 'SERVICE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_server_id'), 'alerts', ['server_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_server_id'), 'api_keys', ['server_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('SERVER_CREATED', 'SERVER_UPDATED', 'SERVER_DELETED', 'API_KEY_CREATED', 'API_KEY_DELETED', 'API_KEY_DEACTIVATED', 'API_KEY_USED', 'ALERT_CREATED', 'ALERT_RESOLVED', 'THRESHOLD_CREATED', 'THRESHOLD_UPDATED', 'THRESHOLD_DELETED', 'CONTAINER_STARTED', 'CONTAINER_STOPPED', 'CONTAINER_RESTARTED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'PASSWORD_CHANGED', 'SETTINGS_UPDATED', name='auditaction'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_server_id'), 'audit_logs', ['server_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('command_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('working_directory', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', name='commandstatus'), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_history_server_id'), 'command_history', ['server_id'], unique=False)
    op.create_index(op.f('ix_command_history_started_at'), 'command_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_command_history_status'), 'command_history', ['status'], unique=False)
    op.create_index(op.f('ix_command_history_user_id'), 'command_history', ['user_id'], unique=False)
    op.create_table('connection_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CONNECTED', 'DISCONNECTED', 'RECONNECTED', 'AUTHENTICATION_FAILED', 'ERROR', name='connectioneventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_events_event_type'), 'connection_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_connection_events_server_id'), 'connection_events', ['server_id'], unique=False)
    op.create_index(op.f('ix_connection_events_timestamp'), 'connection_events', ['timestamp'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('source', sa.Enum('SYSTEM', 'AGENT', 'APPLICATION', 'ALERT', name='logsource'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_level'), 'log_entries', ['level'], unique=False)
    op.create_index(op.f('ix_log_entries_server_id'), 'log_entries', ['server_id'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('cpu_cores', sa.Float(), nullable=True),
    sa.Column('cpu_frequency_mhz', sa.Float(), nullable=True),
    sa.Column('memory_total_gb', sa.Float(), nullable=False),
    sa.Column('memory_used_gb', sa.Float(), nullable=False),
    sa.Column('memory_available_gb', sa.Float(), nullable=False),
    sa.Column('memory_usage_percent', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_available_gb', sa.Float(), nullable=False),
    sa.Column('disk_usage_percent', sa.Float(), nullable=False),
    sa.Column('network_bytes_sent', sa.Float(), nullable=True),
    sa.Column('network_bytes_recv', sa.Float(), nullable=True),
    sa.Column('network_packets_sent', sa.Float(), nullable=True),
    sa.Column('network_packets_recv', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_server_timestamp', 'metrics', ['server_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metrics_server_id'), 'metrics', ['server_id'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_server_id'), table_name='metrics')
    op.drop_index('idx_metrics_server_timestamp', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_server_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_level'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_connection_events_timestamp'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_server_id'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_event_type'), table_name='connection_events')
    op.drop_table('connection_events')
    op.drop_index(op.f('ix_command_history_user_id'), table_name='command_history')
    op.drop_index(op.f('ix_command_history_status'), table_name='command_history')
    op.drop_index(op.f('ix_command_history_started_at'), table_name='command_history')
    op.drop_index(op.f('ix_command_history_server_id'), table_name='command_history')
    op.drop_table('command_history')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_server_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_server_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alerts_server_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_thresholds_server_id'), table_name='alert_thresholds')
    op.drop_table('alert_thresholds')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
